### ISSUE TITLE
Dependencies starting with "@" are lost in markdown

### ISSUE THREAD

**Issue by davegaeddert** [dependencies-io/pullrequest#10]
Not sure how to deal with this, but in npm especially you can have dependencies that start with an "@". The problem is that in GitHub markdown right now those names disappear, I assume because it's trying to find a user or team that matches that handle and coming up with nothing... Might have to contact GitHub about this? Can't seem to `\` it either.

You can look at the raw markdown:
- @storybook/test
- \@storybook/test
- "@storybook/test"
- `@storybook/test`

**Comment by Hypnosphi** [comment]
Enclosing all the package names (not only scoped ones) in backticks sound like a good solution to me

**Comment by davegaeddert** [comment]
Agreed, I think that's probably the thing to do for now.

**Comment by davegaeddert** [comment]
This will go out whenever the next release does.
